React capstone project - Metrics webapp
AyomipoMajek/react-capstone pull request #2
Opened 2023-03-15 19:20 UTC by AyomipoMajek

React capstone project - Metrics webapp created according to microverse requirements which include:

API First you need to choose an API to base the development of the webapp on. The API should allow you to get numeric values based on a parameter. We recommend that you choose an API that is open or needs an API key. If you choose an API that require authentication, you should implement it on your own.

Some example APIs are:

[Financial modeling prep API](https://financialmodelingprep.com/developer/docs/): stock data.
[Air pollution API](https://openweathermap.org/api/air-pollution): air quality data.
You can find many APIs in [this GitHub repo](https://github.com/public-apis/public-apis) or in [ProgrammableWeb](https://www.programmableweb.com/category/all/apis). Some of the APIs requires a token for authentication and some others are just open.

Design

You should follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), including:
Colors (select one main color for your website).
Typography: font face, size and weight.
Layout: composition and space between elements.
Original design idea by [Nelson Sakwa on Behance](https://www.behance.net/sakwadesignstudio).

The [Creative Commons license of the design](https://creativecommons.org/licenses/by-nc/4.0/) requires that you give appropriate credit to the author. Therefore, you must do it in the README of your project.

Interactions

Home page

When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
Along with the category name, you will display some numeric values per category that come from the API.
When the user clicks (or taps) on a category item, the application navigates to the details page.
Details page

In the details page, the webapp retrieves data from the API to show detailed data in the category.
When the user clicks on the "Back" button (<), the user navigates to the home page.
Testing requirements

Create unit tests for pure functions in your Redux code.
Create integration tests for your application using the React Testing Library.
You may need to mock the access to the API, so that your tests don't send actual requests.
You may need to mock the connection to the Redux Store.
Technical requirements

The project is a single-page application (SPA) built with React and Redux.
The data retrieved from the API should be stored in the Redux store.
You should filter the data that you retrieve from the API using a Filter stateless component.
Every page (the main page and the pages for each item) should have a unique route within the SPA.
The project should be deployed and accessible online using [Render](https://render.com/), [Netlify](https://www.netlify.com/) or [GitHub Pages](https://pages.github.com/).
Add a link to the online version of your app to your README file.

2023-03-15 19:42 UTC, huseyinbiyik commented
Hi @AyomipoMajek  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

- Please follow the Gitflow and ask for the review from Pull Request merging from development to main. You can check this [page](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) to learn more.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-15 20:50 UTC, prolajumokeoni commented
Hi @AyomipoMajek, Kindly add the future features section to your readme 👍🏿

2023-03-15 21:01 UTC, prolajumokeoni commented
Hi @AyomipoMajek, Kindly add the future features section to your readme

2023-03-15 22:45 UTC, prolajumokeoni requested changes
Hi @AyomipoMajek 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Your design matches the Behance design
✔️  Home and detail page work correctly 



## Required Changes ♻️

Correct file structure          |  Your file structure
:-------------------------:|:-------------------------:
![Screenshot_771](https://user-images.githubusercontent.com/69638013/225459247-85b588ab-2b4d-494d-bfdf-ae6cd52f41f1.png) | ![Screenshot_772](https://user-images.githubusercontent.com/69638013/225459203-757da083-7e28-484a-ae48-d8d531881101.png)


- [ ] Kindly move the `data `folder to the redux folder and move the redux folder out of the component folder 👍🏿 , this will make your project more organized and follow good file structure  😎 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-15 22:45 UTC, prolajumokeoni commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Kindly fix the broken link to your MIT license page this is currently broken 👍🏿 
- [ ] Kindly delete the template text in your license section
- Doing the above will make your readme more professional

2023-03-15 23:55 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @AyomipoMajek  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2023-03-16 00:02 UTC, MaganaAsiati commented
please check your slack I send you a message

2023-03-27 20:04 UTC, merged